import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const assets = ['rl-gastos.html','manifest.json','src/app.css','src/app.mjs','src/core.mjs','src/store.mjs','src/seeds.mjs','icon-32.png','icon-180.png','icon-192.png','icon-512.png'];
const hash = createHash('sha256');
for (const path of assets) hash.update(path).update(readFileSync(path));
const version = hash.digest('hex').slice(0,16);
const source = `// Generated by scripts/build-sw.mjs. Do not edit manually.
const CACHE_NAME = 'rl-gastos-' + '${version}';
const ASSETS = ${JSON.stringify(assets)};
const ROOT = new URL('./', self.location.href);
const url = path => new URL(path, ROOT).href;
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS.map(path => new Request(url(path), { cache: 'reload' })))));
});
self.addEventListener('message', event => { if (event.data?.type === 'SKIP_WAITING') self.skipWaiting(); });
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('rl-gastos-') && key !== CACHE_NAME).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const request = event.request, target = new URL(request.url);
  if (request.method !== 'GET' || target.origin !== ROOT.origin) return;
  const asset = ASSETS.some(path => url(path) === target.href);
  if (asset) event.respondWith(caches.open(CACHE_NAME).then(cache => cache.match(request).then(cached => cached || fetch(request))));
  else if (request.mode === 'navigate' && (target.pathname === ROOT.pathname || target.pathname === new URL('rl-gastos.html', ROOT).pathname)) {
    event.respondWith(caches.open(CACHE_NAME).then(cache => cache.match(url('rl-gastos.html')).then(cached => cached || fetch(request))));
  }
});
`;
if (process.argv.includes('--check')) {
  if (readFileSync('sw.js','utf8') !== source) throw new Error('Run node scripts/build-sw.mjs to refresh the offline release.');
} else writeFileSync('sw.js',source);
